config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # devise_for :users
	root 'posts#index' , as: 'home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about' =>'pages#about', as: 'about'
  # resource :session

  resources :posts do
	  resources :comments
  end

  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	belongs_to :user
	validates :title,  presence: true,
					length:{minimum: 5}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :posts
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  # rescue_from ::StandardError, with: :handle_err

  private
  def record_not_found
  	render plain: "404 Not Found", status: 404
  end

  # def handle_err(err)
  #   redirect_back(fallback_location: request.referer, notice: '没有这个权限') if err.message == "not_belongs_to_u"
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :user_signed_in?
	# http_basic_authenticate_with name: "likys",password:"1234",only: [:destroy]

	def create
		@post = Post.find(params[:post_id])
		_params = comment_params.merge({user_id: current_user.id})
		@comment = @post.comments.create(_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find_by_id(params[:post_id])
		@comment = current_user.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title='about us'
		@content='this is about pages'
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit , :update , :destroy]
	# http_basic_authenticate_with name: "likys",password: "1234",except: [:index,:show]

	def index
		@posts = Post.all
	end

	def show
		# render :layout => nil
	end

	def new
		@post = Post.new
	end

	def edit
	end

	def update
		if @post.update(post_params)
			ActionCable.server.broadcast 'posts', html: render_to_string('posts/index',layout:false), id: @post.id
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to about_path
	end

	def create
		@post = current_user.posts.new post_params
		if @post.save
			@posts = Post.all
			ActionCable.server.broadcast 'posts', html: render_to_string('posts/index', layout:false), id: @post.id
			redirect_to @post
		else
			render 'new'
		end
	end

	private 
	def post_params
		params.require(:post).permit(:title,:body)
	end

	def find_post
		@post = Post.find(params[:id])
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	
	def new
		
	end

	def create

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<%  @post.comments.each do |comment|%>
	<div class="well">
		<p><Strong><%= link_to comment.user.email, user_path(current_user) %> : </Strong>:<%= comment.body %>

<%= link_to "[X]" ,[comment.post,comment] ,
								method: :delete,
								data: { confirm: 'are you sure ?'}%>
		</p>

	</div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>

<%= form_for([@post, @post.comments.build]) do |f| %>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area(:body,{ :class => 'form-control'}) %>
	</p>
	<p>
		<%= f.submit ({:class => 'btn btn-primary'}) %>
	</p>

	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag   'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>   
   <nav class="navbar navbar-default">
   	<div class ="container">

   	  <div class="navbar-header">
        <span class="navbar-toggler-icon"></span>
      </button>
 	  <a class="navbar-brand" href="#">SimpleBlog</a>
	  </div>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav ">
          <li ><%= link_to "Home",home_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right ">
          <% if user_signed_in? %>
            <li><%= link_to current_user.email, user_path(current_user) %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %>
            <li><%= link_to 'Login', new_user_session_path %>
          <% end %>
        </ul>
         <ul class="nav navbar-nav navbar-right ">
          <% if user_signed_in? %>
            <li ><%= link_to "create Post",new_post_path %></li>
          <% end %>
        </ul>
   	  </div>
     </div>
    </nav>
<div class="container">

    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit posts </h1>
<%= form_for :post , url: post_path(@post), method: :patch do |f|%>
  <% if @post.errors.any? %>
   <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
   <% end %>
  <% end %>
	<p>
		<%= f.label :title%><br>
		<%= f.text_field(:title ,{ :class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area(:body ,{ :class => 'form-control'}) %>
	</p>
	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
	<% end %>

app/views/posts/index.html.erb
<div id="posts">
	<h1>Blog Posts</h1>
	<% @posts.each do |post| %>
		<div class="well">
			<h3><%= link_to post.title, post_path(post) %></h3>
			<p> <%= post.body %></p>
			<p>Author:<%= link_to post.user.email, user_path(post.user) %>  Date:<%= post.user.created_at.strftime("%Y-%m-%d  %H:%M:%S %p") %></p>
			<%= link_to "Read More",post_path(post), :class => 'btn btn_default' %>
		</div>
	<% end %>
</div>

app/views/posts/new.html.erb
<h1>add posts </h1>
<%= form_for :post ,url:posts_path do |f|%>
  <% if @post.errors.any? %>
   <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
   <% end %>
  <% end %>
	<p>
		<%= f.label :title%><br>
		<%= f.text_field(:title ,{ :class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area(:body ,{ :class => 'form-control'}) %>
	</p>
	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
	<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit" ,edit_post_path(@post) ,:class => 'btn btn-default' %>
<%= link_to "Delect" ,post_path(@post) ,
								method: :delete,
								data: { confirm: 'are you sure ?'},
								:class => 'btn btn-danger' %>
<hr>


<%= render 'comments/comments'%>
<%= render 'comments/form' %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <h3>用户信息</h3>
    <%= @user.email %>
</div>

<div class="row">
    <h3>发表过的博文</h3>
    <% if @user.posts.present? %>
        <% @user.posts.each do |post| %>
            <p><%= link_to post.title, post_path(post) %></p>
        <% end %>
    <% else %>
        没有发表的文章
    <% end %>
</div>

<div class="row">
    <h3>发表过的评论</h3>
    <% if @user.comments.present? %>
        <% @user.comments.each do |comment| %>
            <p><%= link_to comment.title, comment_path(comment) %></p>
        <% end %>
    <% else %>
        没有发表的评论
    <% end %>
</div>

<div class="row">
    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Back', users_path %>
    <%= link_to '返回上一页', :back %>
</div>